---
apiVersion: v1
data:
  service-graph: |
    services:
    - isEntrypoint: true
      name: svc-c
      namespace: ns-c
      numReplicas: 1
      responseSize: 1KiB
      script:
      - call:
          extra-header: null
          hostname: svc-c1:8080
          service: svc-c1
          size: 1KiB
      type: http
    - name: svc-c1
      namespace: ns-c
      numReplicas: 1
      responseSize: 1KiB
      script:
      - call:
          extra-header: null
          hostname: svc-c2:8080
          service: svc-c2
          size: 1KiB
      type: http
    - name: svc-c2
      namespace: ns-c
      numReplicas: 1
      responseSize: 1KiB
      script:
      - call:
          extra-header: null
          hostname: svc-c3:8080
          service: svc-c3
          size: 1KiB
      type: http
    - name: svc-c3
      namespace: ns-c
      numReplicas: 1
      responseSize: 1KiB
      type: http
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    isotope: service-graph
  name: service-graph-config
  namespace: ns-c
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-c
  namespace: ns-c
  labels:
    app: svc-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-c
    role: service
  name: svc-c
  namespace: ns-c
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-c
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      creationTimestamp: "2023-12-11T14:07:30Z"
      labels:
        name: svc-c
        role: service
    spec:
      serviceAccountName: svc-c
      containers:
      - args:
        - --max-idle-connections-per-host=0
        env:
        - name: SERVICE_NAME
          value: svc-c
        image: ghcr.io/tetratecx/tsb-single-vm/graph-server:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-c
    role: service
  name: svc-c
  namespace: ns-c
spec:
  ports:
  - name: http-web
    port: 8080
    targetPort: 0
  selector:
    name: svc-c
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-c1
  namespace: ns-c
  labels:
    app: svc-c1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-c1
    role: service
  name: svc-c1
  namespace: ns-c
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-c1
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      creationTimestamp: "2023-12-11T14:07:30Z"
      labels:
        name: svc-c1
        role: service
    spec:
      serviceAccountName: svc-c1
      containers:
      - args:
        - --max-idle-connections-per-host=0
        env:
        - name: SERVICE_NAME
          value: svc-c1
        image: ghcr.io/tetratecx/tsb-single-vm/graph-server:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-c1
    role: service
  name: svc-c1
  namespace: ns-c
spec:
  ports:
  - name: http-web
    port: 8080
    targetPort: 0
  selector:
    name: svc-c1
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-c2
  namespace: ns-c
  labels:
    app: svc-c2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-c2
    role: service
  name: svc-c2
  namespace: ns-c
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-c2
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      creationTimestamp: "2023-12-11T14:07:30Z"
      labels:
        name: svc-c2
        role: service
    spec:
      serviceAccountName: svc-c2
      containers:
      - args:
        - --max-idle-connections-per-host=0
        env:
        - name: SERVICE_NAME
          value: svc-c2
        image: ghcr.io/tetratecx/tsb-single-vm/graph-server:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-c2
    role: service
  name: svc-c2
  namespace: ns-c
spec:
  ports:
  - name: http-web
    port: 8080
    targetPort: 0
  selector:
    name: svc-c2
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-c3
  namespace: ns-c
  labels:
    app: svc-c3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-c3
    role: service
  name: svc-c3
  namespace: ns-c
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-c3
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      creationTimestamp: "2023-12-11T14:07:30Z"
      labels:
        name: svc-c3
        role: service
    spec:
      serviceAccountName: svc-c3
      containers:
      - args:
        - --max-idle-connections-per-host=0
        env:
        - name: SERVICE_NAME
          value: svc-c3
        image: ghcr.io/tetratecx/tsb-single-vm/graph-server:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-c3
    role: service
  name: svc-c3
  namespace: ns-c
spec:
  ports:
  - name: http-web
    port: 8080
    targetPort: 0
  selector:
    name: svc-c3
status:
  loadBalancer: {}
