---
apiVersion: v1
data:
  service-graph: |
    services:
    - isEntrypoint: true
      name: svc-b
      namespace: ns-b
      numReplicas: 1
      responseSize: 1KiB
      script:
      - call:
          extra-header: null
          hostname: svc-b1:8080
          service: svc-b1
          size: 1KiB
      - call:
          extra-header: null
          hostname: svc-b2:8080
          service: svc-b2
          size: 1KiB
      - call:
          extra-header: null
          hostname: svc-b3:8080
          service: svc-b3
          size: 1KiB
      type: http
    - name: svc-b1
      namespace: ns-b
      numReplicas: 1
      responseSize: 1KiB
      type: http
    - name: svc-b2
      namespace: ns-b
      numReplicas: 1
      responseSize: 1KiB
      type: http
    - name: svc-b3
      namespace: ns-b
      numReplicas: 1
      responseSize: 1KiB
      type: http
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    isotope: service-graph
  name: service-graph-config
  namespace: ns-b
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-b
  namespace: ns-b
  labels:
    app: svc-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-b
    role: service
  name: svc-b
  namespace: ns-b
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-b
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      creationTimestamp: "2023-12-11T14:07:30Z"
      labels:
        name: svc-b
        role: service
    spec:
      serviceAccountName: svc-b
      containers:
      - args:
        - --max-idle-connections-per-host=0
        env:
        - name: SERVICE_NAME
          value: svc-b
        image: ghcr.io/tetratecx/tsb-single-vm/graph-server:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-b
    role: service
  name: svc-b
  namespace: ns-b
spec:
  ports:
  - name: http-web
    port: 8080
    targetPort: 0
  selector:
    name: svc-b
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-b1
  namespace: ns-b
  labels:
    app: svc-b1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-b1
    role: service
  name: svc-b1
  namespace: ns-b
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-b1
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      creationTimestamp: "2023-12-11T14:07:30Z"
      labels:
        name: svc-b1
        role: service
    spec:
      serviceAccountName: svc-b1
      containers:
      - args:
        - --max-idle-connections-per-host=0
        env:
        - name: SERVICE_NAME
          value: svc-b1
        image: ghcr.io/tetratecx/tsb-single-vm/graph-server:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-b1
    role: service
  name: svc-b1
  namespace: ns-b
spec:
  ports:
  - name: http-web
    port: 8080
    targetPort: 0
  selector:
    name: svc-b1
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-b2
  namespace: ns-b
  labels:
    app: svc-b2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-b2
    role: service
  name: svc-b2
  namespace: ns-b
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-b2
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      creationTimestamp: "2023-12-11T14:07:30Z"
      labels:
        name: svc-b2
        role: service
    spec:
      serviceAccountName: svc-b2
      containers:
      - args:
        - --max-idle-connections-per-host=0
        env:
        - name: SERVICE_NAME
          value: svc-b2
        image: ghcr.io/tetratecx/tsb-single-vm/graph-server:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-b2
    role: service
  name: svc-b2
  namespace: ns-b
spec:
  ports:
  - name: http-web
    port: 8080
    targetPort: 0
  selector:
    name: svc-b2
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-b3
  namespace: ns-b
  labels:
    app: svc-b3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-b3
    role: service
  name: svc-b3
  namespace: ns-b
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-b3
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      creationTimestamp: "2023-12-11T14:07:30Z"
      labels:
        name: svc-b3
        role: service
    spec:
      serviceAccountName: svc-b3
      containers:
      - args:
        - --max-idle-connections-per-host=0
        env:
        - name: SERVICE_NAME
          value: svc-b3
        image: ghcr.io/tetratecx/tsb-single-vm/graph-server:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-12-11T14:07:30Z"
  labels:
    app: svc-b3
    role: service
  name: svc-b3
  namespace: ns-b
spec:
  ports:
  - name: http-web
    port: 8080
    targetPort: 0
  selector:
    name: svc-b3
status:
  loadBalancer: {}
