---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-c
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-c
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-d
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-e
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-e
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-f
  labels:
    istio-injection: enabled

