apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tsb
commonLabels:
  app: pgadmin
images:
  - name: pgadmin4
    newTag: "6.21"
    newName: dpage/pgadmin4
resources:
  - resources/deployment.yaml
  - resources/loadbalancer.yaml
