---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-def
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-d
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-e
  labels:
    istio-injection: enabled
