apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          imagePullPolicy: IfNotPresent
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@tetrate.io"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
            - name: PGADMIN_PORT
              value: "80"
            - name: PGADMIN_SERVER_JSON_FILE
              value: "/pgadmin4/servers.json"
          ports:
            - containerPort: 80
              name: pgadminport
          volumeMounts:
            - name: servers-json
              subPath: servers.json
              mountPath: /pgadmin4/servers.json
            - name: pgpass
              subPath: pgpass
              mountPath: /pgpass
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: servers-json
          configMap:
            name: servers.json
        - name: pgpass
          configMap:
            name: pgpass
            defaultMode: 0600
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: pgadmin
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: ClusterIP
