---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: gw-tier1-ws
  name: gw-tier1-group
spec:
  displayName: GatewayTier1_Group
  namespaceSelector:
    names:
      - "demo/gateway-tier1"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
Metadata:
  organization: tetrate
  tenant: prod
  workspace: gw-abc-ws
  name: gw-abc-group
spec:
  displayName: GatewayABC_GatewayGroup
  namespaceSelector:
    names:
      - "*/gateway-abc"
  configMode: BRIDGED
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-a-ws
  name: app-a-traffic-group
spec:
  displayName: AppA_TrafficGroup
  namespaceSelector:
    names:
      - "*/ns-a"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-a-ws
  name: app-a-security-group
spec:
  displayName: AppA_SecurityGroup
  namespaceSelector:
    names:
      - "*/ns-a"
  configMode: BRIDGED
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-b-ws
  name: app-b-traffic-group
spec:
  displayName: AppB_TrafficGroup
  namespaceSelector:
    names:
      - "*/ns-b"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-b-ws
  name: app-b-security-group
spec:
  displayName: AppB_SecurityGroup
  namespaceSelector:
    names:
      - "*/ns-b"
  configMode: BRIDGED
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-c-ws
  name: app-c-traffic-group
spec:
  displayName: AppC_TrafficGroup
  namespaceSelector:
    names:
      - "*/ns-c"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: prod
  workspace: app-c-ws
  name: app-c-security-group
spec:
  displayName: AppC_SecurityGroup
  namespaceSelector:
    names:
      - "*/ns-c"
  configMode: BRIDGED
