apiVersion: api.tsb.tetrate.io/v2
kind: Cluster
metadata:
  organization: tetrate
  name: demo
spec:
  locality:
    region: region1
  tier1Cluster: true
  tokenTtl: 31536000s
  network: tier1
---
apiVersion: api.tsb.tetrate.io/v2
kind: Cluster
metadata:
  organization: tetrate
  name: active-cluster
spec:
  locality:
    region: region1
  tier1Cluster: false
  tokenTtl: 31536000s
  network: tier2
---
apiVersion: api.tsb.tetrate.io/v2
kind: Cluster
metadata:
  organization: tetrate
  name: standby-cluster
spec:
  locality:
    region: region2
  tier1Cluster: false
  tokenTtl: 31536000s
  network: tier2
---
