---
apiVersion: v1
data:
  service-graph: |
    services:
    - isEntrypoint: true
      name: svc-c
      namespace: ns-c
      numReplicas: 1
      responseSize: 1KiB
      script:
      - call:
          extra-header: null
          hostname: svc-c1:8080
          service: svc-c1
          size: 1KiB
      type: http
    - name: svc-c1
      namespace: ns-c
      numReplicas: 1
      responseSize: 1KiB
      script:
      - call:
          extra-header: null
          hostname: svc-c2:8080
          service: svc-c2
          size: 1KiB
      type: http
    - name: svc-c2
      namespace: ns-c
      numReplicas: 1
      responseSize: 1KiB
      script:
      - call:
          extra-header: null
          hostname: svc-c3:8080
          service: svc-c3
          size: 1KiB
      type: http
    - errorRate: 100%
      name: svc-c3
      namespace: ns-c
      numReplicas: 1
      responseSize: 1KiB
      type: http
kind: ConfigMap
metadata:
  creationTimestamp: '2023-12-11T14:07:30Z'
  labels:
    isotope: service-graph
  name: service-graph-config
  namespace: ns-c
