---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-g
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-h
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-i
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-ghi
