---
apiVersion: config.agent.onboarding.tetrate.io/v1alpha1
kind: OnboardingConfiguration
onboardingEndpoint:
  host: __TSB_VM_ONBOARDING_ENDPOINT__
  transportSecurity:
    tls:
      insecureSkipVerify: true
      sni: vm-onboarding.tetrate.prod
workloadGroup:
  namespace: ns-b
  name: app-b
workload:
  labels:
    app: app-b
    version: v1
